name: Stop all workflows

on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      
  stop-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const workflows = await (
              github.rest.actions.listRepoWorkflows.endpoint.merge(context.repo)
            );

            core.info(JSON.stringify(workflows));
